---
title: "merge"
output: html_document
---

```{r}
library(here)
library(dplyr)
library(readr)
library(lubridate)
dir <- file.path("unified_data", "full-output", "complaints")
```

## Complaint data

```{r}
# Read in complaint - accused officer data
accused <-
    read_csv(here(dir, "complaints-accused.csv"),
             col_types = cols(recc_finding = "c", recc_outcome = "c",
                              cr_id = "c")) %>%
    mutate(link_UID = as.character(link_UID),
           final_outcome = tolower(final_outcome),
           recc_outcome = tolower(recc_outcome))

#  Read in civilian witnesses to the complaint
civWitness <-
    read_csv(here(dir, "complaints-civilian-witnesses_2000-2018_2018-03.csv"),
             col_types = cols(complaint_date = col_date(format = "%Y-%m-%d"),
                              cr_id = "c")) %>%
    mutate(birth_year_date = ymd(birth_year, truncated = 3),
           age = floor(time_length(difftime(complaint_date, birth_year_date),
                                   "years")))

# Read in complaints by complainants
complainants <-
    read_csv(here(dir, "complaints-complainants.csv"),
             col_types = cols(cr_id = "c"))

# Read in Chicago police officers witnesses to the complaint
# 2018 dataset is a subset of this dataset with more extensive information
# made available about the officers who witnessed the violation or crime
cpdWitness <-
    read_csv(here(dir, "complaints-CPD-witnesses.csv"),
             col_types = cols(cr_id = "c")) %>%
    mutate(link_UID = as.character(link_UID))

# Read in investigators who are investigating the cases
# Some of these people don't have officer IDs.
# Investigator ID uniquely identifies each investigator I think
# ID for investigators, If non-null UID = UID, else cv * 100,000 + intrafile id
investigators <-
    read_csv(here(dir, "complaints-investigators.csv"),
             col_types = cols(assigned_datetime = "c", first_name_NS = "c",
                              gender = "c", investigator_type = "c",
                              `complaints-investigators_2000-2018_2018-03_ID` = "d",
                              last_name_NS = "c", race = "c", birth_year = "d",
                              star = "d")) %>%
    mutate(link_UID = as.character(link_UID), cr_id = as.character(cr_id),
           investigator_ID = as.character(investigator_ID))

# Read in the victims
victims <-
    read_csv(here(dir, "complaints-victims.csv")) %>%
    mutate(cr_id = as.character(cr_id))

# Read in complaint locations
locations <-
    read_csv(here(dir, "complaints-complaints.csv"),
             col_types = cols(cr_id = "c", full_address = "c"))
```

## Police information

```{r}
# Unit history for each police officer. Each unit they were a part of and for
# how long.
unitHistory <-
    read_csv(here("unified_data", "full-output", "unit-history",
                  "unit-history.csv"))

# The 2018 roster has newly sworn in officers after 2016 plus some officers with
# missing ID numbers.
roster <-
    read_csv(here("unified_data", "full-output", "roster",
                        "roster_1936-2017_2017-04.csv"),
             col_types = cols(star7 = "d", star8 = "d", star9 = "d",
                              star10 = "d", middle_initial2 = "c")) %>%
    mutate(link_UID = as.character(link_UID))
    

roster2018 <-
    read_csv(here("unified_data", "full-output", "roster",
                  "roster__2018-03.csv"),
             col_types = cols(middle_initial2 = "c")) %>%
    mutate(link_UID = as.character(link_UID))

df <- roster %>% filter(!(link_UID %in% roster2018$link_UID))
df2 <- roster2018 %>% filter(!(link_UID %in% roster$link_UID))

# Officer profiles and final profiles are the same
profile <-
    read_csv(here("unified_data", "full-output", "profiles",
                  "final-profiles.csv"),
             col_types = cols(middle_initial2 = "c"))

df3 <- profile %>% filter(!(link_UID %in% roster$link_UID))
df4 <- roster %>% filter(!(link_UID %in% profile$link_UID))
df5 <- roster2018 %>% filter(!(link_UID %in% profile$link_UID))

officer_reference <-
    read_csv(here("unified_data", "full-output", "profiles",
                  "officer-reference.csv"),
             col_types = cols(middle_initial2 = "c")) %>%
    mutate(link_UID = as.character(link_UID))
```

## Awards

```{r}
awards <-
    read_csv(here("unified_data", "full-output", "awards",
                  "awards_1967-2017_2017-08.csv"),
             col_types = cols(ceremony_date = "c")) %>%
    mutate(link_UID = as.character(link_UID))
```

## Salary

```{r}
salary <-
    read_csv(here("unified_data", "full-output", "salary",
                  "salary_2002-2017_2017-09.csv"),
             col_types = cols(`salary-2003_2002-2017_2017-09_ID` = "d",
                              `salary-2004_2002-2017_2017-09_ID` = "d",
                              `salary-2005_2002-2017_2017-09_ID` = "d",
                              `salary-2006_2002-2017_2017-09_ID` = "d",
                              `salary-2007_2002-2017_2017-09_ID` = "d",
                              `salary-2008_2002-2017_2017-09_ID` = "d",
                              `salary-2009_2002-2017_2017-09_ID` = "d",
                              `salary-2010_2002-2017_2017-09_ID` = "d",
                              `salary-2011_2002-2017_2017-09_ID` = "d",
                              `salary-2012_2002-2017_2017-09_ID` = "d",
                              `salary-2013_2002-2017_2017-09_ID` = "d",
                              `salary-2014_2002-2017_2017-09_ID` = "d",
                              `salary-2015_2002-2017_2017-09_ID` = "d",
                              `salary-2016_2002-2017_2017-09_ID` = "d",
                              `salary-2017_2002-2017_2017-09_ID` = "d")) %>%
    mutate(link_UID = as.character(link_UID))

salaryFilled <-
    read_csv(here("unified_data", "full-output", "salary",
                  "salary-filled_2002-2017_2017-09.csv"),
             col_types = cols(`salary-2003_2002-2017_2017-09_ID` = "d",
                              `salary-2004_2002-2017_2017-09_ID` = "d",
                              `salary-2005_2002-2017_2017-09_ID` = "d",
                              `salary-2006_2002-2017_2017-09_ID` = "d",
                              `salary-2007_2002-2017_2017-09_ID` = "d",
                              `salary-2008_2002-2017_2017-09_ID` = "d",
                              `salary-2009_2002-2017_2017-09_ID` = "d",
                              `salary-2010_2002-2017_2017-09_ID` = "d",
                              `salary-2011_2002-2017_2017-09_ID` = "d",
                              `salary-2012_2002-2017_2017-09_ID` = "d",
                              `salary-2013_2002-2017_2017-09_ID` = "d",
                              `salary-2014_2002-2017_2017-09_ID` = "d",
                              `salary-2015_2002-2017_2017-09_ID` = "d",
                              `salary-2016_2002-2017_2017-09_ID` = "d",
                              `salary-2017_2002-2017_2017-09_ID` = "d",
                              gap = "c",
                              gen = "d")) %>%
    mutate(link_UID = as.character(link_UID))

a <- salary %>% count(link_UID)
b <- salaryFilled %>% count(link_UID)
join <- full_join(a, b, by = "link_UID")
filtr <- join %>% filter(n.x != n.y)

salaryRanks <-
    read_csv(here("unified_data", "full-output", "salary",
                  "salary-ranks_2002-2017_2017-09.csv")) %>%
    mutate(link_UID = as.character(link_UID))

a <- salary %>% count(link_UID)
b <- salaryRanks %>% count(link_UID)
join <- full_join(a, b, by = "link_UID")
filtr <- join %>% filter(n.x != n.y)
```

## Settlements

```{r}
settlements <-
    read_csv(here("unified_data", "full-output", "settlements",
                  "settlements_1952-2016_2017-01.csv"))
```

## Use of Force

```{r}
trrDir <- file.path("unified_data", "full-output", "TRR")

# Read in the officer actions
trrActions <-
    read_csv(here(trrDir, "TRR-actions-responses_2004-2016_2016-09.csv")) %>%
    mutate(trr_id = as.character(trr_id))

# Read what the subjects were charged with? I think
trrCharges <-
    read_csv(here(trrDir, "TRR-charges_2004-2016_2016-09.csv")) %>%
    mutate(trr_id = as.character(trr_id))

# Every use of force which resulted in a weapon being discharged
trrDischarge <-
    read_csv(here(trrDir, "TRR-discharge-hits_2004-2016_2016-09.csv"))

# Each police officer involved with each use of force
trrOfficers <-
    read_csv(here(trrDir, "TRR-officers_2004-2016_2016-09.csv")) %>%
    mutate(link_UID = as.character(link_UID))

# Don't really know what this dataset is. Status of the use of force reports?
trrStatus <-
    read_csv(here(trrDir, "TRR-statuses_2004-2016_2016-09.csv")) %>%
    mutate(link_UID = as.character(link_UID),
           trr_id = as.character(link_UID))

# Weapons wielded by subject if they were wielding a weapon
trrSubjectWeapon <-
    read_csv(here(trrDir, "TRR-subject-weapons_2004-2016_2016-09.csv"))

# Subjects in the use of force
trrSubjects <-
    read_csv(here(trrDir, "TRR-subjects_2004-2016_2016-09.csv"))

# Superset of all weapon discharges and not just guns/firearms, I think
trrWeaponDischarge <-
    read_csv(here(trrDir, "TRR-weapon-discharges_2004-2016_2016-09.csv"))

# Main list of TRR incidents it seems
trrMain <-
    read_csv(here(trrDir, "TRR-main_2004-2016_2016-09.csv"))
```
