---
title: "create_dep_vars"
format: pdf
---

```{r}
library(knitr)
opts_chunk$set(message = F, echo = F, warning = F)

library(here)
source(here("functions.R"))
```

```{r}
unit_shift_net <- readRDS(here("create-networks", "output", "unit_shift_net_bp.rds"))
stop_net <- readRDS(here("create-networks", "output", "stop_net_bp.rds"))
arrest_net <- readRDS(here("create-networks", "output", "arrest_net_bp.rds"))

officers <-
    my_read_csv(here("create-networks", "input", "active_officers_ba.csv")) %>%
    mutate(age = 2015 - birth_year,
           years_exp = (ymd("2015-12-01") - appointed_month) / dyears(1)) %>%
    select(-birth_year, -appointed_month)
```

## Create dependent variables (i.e., shift matrix, stop matrix, arrest matrix)

I have to create the adjacency matrices in this convoluted fashion in order for them to have the same ordering as the matrices for the independent variables.

```{r}
shift_matrix <-
    as_data_frame(unit_shift_net, what = "edges") %>%
    graph_from_data_frame(directed = F, vertices = officers) %>%
    as_adjacency_matrix(sparse = F, attr = "weight")

stop_matrix <-
    as_data_frame(stop_net, what = "edges") %>%
    graph_from_data_frame(directed = F, vertices = officers) %>%
    as_adjacency_matrix(sparse = F, attr = "weight")

arrest_matrix <-
    as_data_frame(arrest_net, what = "edges") %>%
    graph_from_data_frame(directed = F, vertices = officers) %>%
    as_adjacency_matrix(sparse = F, attr = "weight")

table(rownames(shift_matrix) == rownames(stop_matrix))
table(rownames(shift_matrix) == rownames(arrest_matrix))
table(colnames(shift_matrix) == colnames(stop_matrix))
table(colnames(shift_matrix) == colnames(arrest_matrix))
```

```{r}
save(shift_matrix, stop_matrix, arrest_matrix,
     file = here("create-networks", "output", "dv_matrices.Rda"))
```
